root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/server ./cmd/server"
  bin = "./tmp/server"
  delay = 1000
  exclude_dir = ["tmp", "vendor"]
  include_ext = ["go"]
  exclude_regex = ["_test\\.go"]
  kill_delay = "0.5s"
  rerun = false

[log]
  time = true
  main_only = false

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[misc]
  clean_on_exit = true
